In [147]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [148]:
import seaborn as sns
df=sns.load_dataset("titanic")
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [149]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [150]:
df

     survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...   NaN  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...   NaN  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...   NaN  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [152]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [153]:
numcol=df.select_dtypes(include="number").columns

In [154]:
df[numcol]=df[numcol].fillna(df[numcol].median())

In [155]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [156]:
objcol = df.select_dtypes(include="object").columns

In [157]:
objcol

Index(['sex', 'embarked', 'who', 'embark_town', 'alive'], dtype='object')

In [158]:
for col in objcol:
    df[col]=df[col].fillna(df[col].mode()[0])

In [159]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [160]:
catcol = df.select_dtypes(include="category").columns

In [161]:
for col in catcol:
    df[col]=df[col].fillna(df[col].mode()[0])
df

     survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0           0       3    male  22.0  ...     C  Southampton     no  False
1           1       1  female  38.0  ...     C    Cherbourg    yes  False
2           1       3  female  26.0  ...     C  Southampton    yes   True
3           1       1  female  35.0  ...     C  Southampton    yes  False
4           0       3    male  35.0  ...     C  Southampton     no   True
..        ...     ...     ...   ...  ...   ...          ...    ...    ...
886         0       2    male  27.0  ...     C  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female  28.0  ...     C  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...     C   Queenstown     no   True

[891 rows x 15 columns]

In [162]:


df = pd.get_dummies(df, drop_first=True)
df

     survived  pclass  ...  embark_town_Southampton  alive_yes
0           0       3  ...                     True      False
1           1       1  ...                    False       True
2           1       3  ...                     True       True
3           1       1  ...                     True       True
4           0       3  ...                     True      False
..        ...     ...  ...                      ...        ...
886         0       2  ...                     True      False
887         1       1  ...                     True       True
888         0       3  ...                     True      False
889         1       1  ...                    False       True
890         0       3  ...                    False      False

[891 rows x 24 columns]

In [163]:
x=df.drop("alive_yes",axis=1)

In [164]:
y=df["alive_yes"]

In [165]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [166]:
model=RandomForestClassifier()

In [167]:
params={
    'n_estimators':[100,200,300],
    'max_depth':[5,7,9,11],
    'min_samples_leaf':[2,4,6,8],
    'min_samples_split':[2,4,5]
}
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(param_grid=params,estimator=model,cv=5,n_jobs=-1,scoring='accuracy')
grid.fit(x_train,y_train)
best_params=grid.best_params_
best_model=grid.best_estimator_
print(best_params)
print(best_model)

{'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 300}
RandomForestClassifier(max_depth=5, min_samples_leaf=2, n_estimators=300)